"""Regenerate the link-preview card at static/og.png.

This exists as a script rather than a one-off because the card carries the
product name, and the name has already changed twice. A card generated by
hand drifts silently: nothing in the test suite can read a PNG, so a stale
name survives every check and only shows up in somebody's Slack unfurl.

    python3 scripts/make_og.py

Figures come from the live database when one is present, so the card shows
the same coverage the landing page does. With no database it falls back to
naming no numbers at all -- an invented figure on a shareable image is the
worst place to put one.
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
STATIC = ROOT / "src" / "vriddhix" / "api" / "static"

NAME = "Pramana"
TAGLINE = "A research instrument for Indian equities"
LINE = ("Chart structure measured on NSE, with every failed breakout kept "
        "in the ledger.")


def coverage() -> str:
    """Bars, sessions and patterns from the database, or an empty string."""
    sys.path.insert(0, str(ROOT / "src"))
    try:
        from sqlalchemy import func, select

        from vriddhix.db.models import OhlcvDaily, Pattern, ScanRun
        from vriddhix.db.base import session_scope

        with session_scope() as s:
            bars = s.scalar(select(func.count()).select_from(OhlcvDaily)) or 0
            scans = s.scalar(
                select(func.count()).select_from(ScanRun)
                .where(ScanRun.status == "COMPLETED")
            ) or 0
            pats = s.scalar(select(func.count()).select_from(Pattern)) or 0
        if not bars:
            return ""
        return (f"{bars:,} bars &nbsp;·&nbsp; {scans:,} sessions "
                f"&nbsp;·&nbsp; {pats:,} patterns")
    except Exception as exc:  # no database here, or it has moved
        print(f"  (no coverage figures: {exc})", file=sys.stderr)
        return ""


HTML = """
<!doctype html><meta charset="utf-8">
<style>
  @font-face {{ font-family: x; src: local("Georgia"); }}
  * {{ margin:0; box-sizing:border-box }}
  body {{
    width:1200px; height:630px; display:flex; flex-direction:column;
    justify-content:center; padding:0 86px 60px; background:#0e1116; color:#e9edf2;
    font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
    position:relative; overflow:hidden;
  }}
  /* the regime ribbon, same idea as the page: measured, not decorative */
  .ribbon {{
    position:absolute; inset:auto 0 0 0; height:118px; display:flex; opacity:.55;
    -webkit-mask-image:linear-gradient(to bottom,transparent,#000 78%);
  }}
  .ribbon i {{ flex:1 }}
  .glow {{
    position:absolute; width:720px; height:720px; right:-230px; top:-250px;
    background:radial-gradient(circle,rgba(224,173,116,.16),transparent 66%);
  }}
  .mark {{ display:flex; align-items:center; gap:20px; margin-bottom:30px }}
  .mark img {{ width:62px; height:62px }}
  .mark b {{ font-size:46px; font-weight:620; letter-spacing:-.6px }}
  .mark span {{
    font-size:15px; letter-spacing:2.4px; text-transform:uppercase;
    color:#e0ad74; border:1px solid rgba(224,173,116,.42);
    border-radius:5px; padding:5px 11px; font-weight:600;
  }}
  h1 {{ font-size:59px; line-height:1.09; letter-spacing:-1.5px; font-weight:640 }}
  p  {{ font-size:26px; line-height:1.45; color:#98a3b2; margin-top:22px; max-width:940px }}
  .nums {{
    margin-top:38px; font-size:21px; color:#e0ad74; font-weight:600;
    font-variant-numeric:tabular-nums;
  }}
</style>
<div class="glow"></div>
<div class="mark">
  <img src="logo.svg"><b>{name}</b><span>NSE</span>
</div>
<h1>{tagline}</h1>
<p>{line}</p>
<div class="nums">{nums}</div>
<div class="ribbon">{ribbon}</div>
"""


def main() -> int:
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("playwright is not installed: pip install playwright", file=sys.stderr)
        return 1

    # A real regime sequence shape: long neutral, a break down, a recovery.
    scores = [52, 55, 58, 54, 49, 44, 38, 30, 22, 16, 12, 9, 14, 21, 29,
              36, 41, 47, 53, 58, 62, 66, 61, 55, 48, 40, 33, 27, 22, 18]

    def fill(v: int) -> str:
        if v >= 65:
            return "#2f9e6b"
        if v >= 45:
            return "#c9a227"
        if v >= 25:
            return "#c8623c"
        return "#b2413b"

    ribbon = "".join(f'<i style="background:{fill(v)}"></i>' for v in scores)
    html = HTML.format(name=NAME, tagline=TAGLINE, line=LINE,
                       nums=coverage(), ribbon=ribbon)

    out = STATIC / "og.png"
    tmp = STATIC / "_og.html"
    tmp.write_text(html)
    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch()
            page = browser.new_page(viewport={"width": 1200, "height": 630},
                                    device_scale_factor=1)
            page.goto(tmp.as_uri())
            page.wait_for_timeout(350)
            page.screenshot(path=str(out))
            browser.close()
    finally:
        tmp.unlink(missing_ok=True)

    print(f"wrote {out} ({out.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
