"""Phase 1 foundation: reference data, universe, prices, features, ops.

Revision ID: 0001
Revises:
Create Date: 2026-09-14

Written by hand rather than autogenerated so that the Timescale hypertable
conversion and the portability choices are explicit and reviewable.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

PRICE = sa.Numeric(18, 4)
VOLUME = sa.Numeric(20, 2)
RATIO = sa.Numeric(18, 6)
PCT = sa.Numeric(12, 6)


def _timestamps() -> list[sa.Column]:
    return [
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
    ]


def upgrade() -> None:
    # -- reference ------------------------------------------------------
    op.create_table(
        "sectors",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("code", sa.String(32), nullable=False),
        sa.Column("name", sa.String(128), nullable=False),
        *_timestamps(),
        sa.UniqueConstraint("code", name="uq_sectors_code"),
    )

    op.create_table(
        "industries",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("sector_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(48), nullable=False),
        sa.Column("name", sa.String(128), nullable=False),
        *_timestamps(),
        sa.ForeignKeyConstraint(["sector_id"], ["sectors.id"],
                                name="fk_industries_sector_id_sectors"),
        sa.UniqueConstraint("sector_id", "code", name="uq_industries_sector_id_code"),
    )
    op.create_index("ix_industries_sector_id", "industries", ["sector_id"])

    op.create_table(
        "stocks",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("symbol", sa.String(32), nullable=False),
        sa.Column("name", sa.String(160), nullable=False),
        sa.Column("isin", sa.String(12), nullable=True),
        sa.Column("exchange", sa.String(8), nullable=False, server_default="NSE"),
        sa.Column("industry_id", sa.Integer(), nullable=True),
        sa.Column("lot_size", sa.Integer(), nullable=False, server_default="1"),
        # Delisted names are retained, flagged. Deleting them is how
        # survivorship bias becomes unrecoverable.
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("listed_on", sa.Date(), nullable=True),
        sa.Column("delisted_on", sa.Date(), nullable=True),
        *_timestamps(),
        sa.ForeignKeyConstraint(["industry_id"], ["industries.id"],
                                name="fk_stocks_industry_id_industries"),
        sa.UniqueConstraint("symbol", name="uq_stocks_symbol"),
        sa.UniqueConstraint("isin", name="uq_stocks_isin"),
    )
    op.create_index("ix_stocks_exchange_is_active", "stocks", ["exchange", "is_active"])
    op.create_index("ix_stocks_industry_id", "stocks", ["industry_id"])

    op.create_table(
        "indices",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("code", sa.String(32), nullable=False),
        sa.Column("name", sa.String(128), nullable=False),
        sa.Column("is_benchmark", sa.Boolean(), nullable=False, server_default=sa.false()),
        *_timestamps(),
        sa.UniqueConstraint("code", name="uq_indices_code"),
    )

    # -- universe -------------------------------------------------------
    op.create_table(
        "universe_members",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("index_id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("source", sa.String(16), nullable=False, server_default="declared"),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["index_id"], ["indices.id"],
                                name="fk_universe_members_index_id_indices"),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"],
                                name="fk_universe_members_stock_id_stocks"),
        sa.UniqueConstraint("index_id", "stock_id", "effective_from",
                            name="uq_universe_members_index_id_stock_id_effective_from"),
        sa.CheckConstraint("effective_to IS NULL OR effective_to > effective_from",
                           name="ck_universe_members_effective_range"),
    )
    op.create_index("ix_universe_members_index_id_effective_from_effective_to",
                    "universe_members", ["index_id", "effective_from", "effective_to"])
    op.create_index("ix_universe_members_stock_id", "universe_members", ["stock_id"])

    op.create_table(
        "universe_snapshots",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("index_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(64), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("member_count", sa.Integer(), nullable=False, server_default="0"),
        # False means built without real membership history; runs referencing
        # it must surface a survivorship warning.
        sa.Column("is_complete", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["index_id"], ["indices.id"],
                                name="fk_universe_snapshots_index_id_indices"),
        sa.UniqueConstraint("version", name="uq_universe_snapshots_version"),
    )
    op.create_index("ix_universe_snapshots_index_id", "universe_snapshots", ["index_id"])

    # -- prices ---------------------------------------------------------
    op.create_table(
        "ohlcv_daily",
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", PRICE, nullable=False),
        sa.Column("high", PRICE, nullable=False),
        sa.Column("low", PRICE, nullable=False),
        sa.Column("close", PRICE, nullable=False),
        sa.Column("volume", VOLUME, nullable=False, server_default="0"),
        sa.Column("adj_close", PRICE, nullable=True),
        sa.Column("adj_factor", sa.Numeric(18, 8), nullable=False, server_default="1"),
        sa.Column("provider", sa.String(24), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE",
                                name="fk_ohlcv_daily_stock_id_stocks"),
        sa.PrimaryKeyConstraint("stock_id", "date", name="pk_ohlcv_daily"),
        sa.CheckConstraint("high >= low", name="ck_ohlcv_daily_high_ge_low"),
        sa.CheckConstraint("volume >= 0", name="ck_ohlcv_daily_volume_non_negative"),
    )
    op.create_index("ix_ohlcv_daily_date", "ohlcv_daily", ["date"])

    # -- features -------------------------------------------------------
    op.create_table(
        "technical_features",
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("ema_20", PRICE, nullable=True),
        sa.Column("ema_50", PRICE, nullable=True),
        sa.Column("ema_100", PRICE, nullable=True),
        sa.Column("ema_200", PRICE, nullable=True),
        sa.Column("atr_14", RATIO, nullable=True),
        sa.Column("atr_pct", PCT, nullable=True),
        sa.Column("avg_volume_20", VOLUME, nullable=True),
        sa.Column("avg_volume_50", VOLUME, nullable=True),
        sa.Column("rel_volume", sa.Numeric(12, 4), nullable=True),
        sa.Column("ret_1m", PCT, nullable=True),
        sa.Column("ret_3m", PCT, nullable=True),
        sa.Column("ret_6m", PCT, nullable=True),
        sa.Column("ret_12m", PCT, nullable=True),
        sa.Column("high_52w", PRICE, nullable=True),
        sa.Column("low_52w", PRICE, nullable=True),
        sa.Column("pct_from_52w_high", PCT, nullable=True),
        sa.Column("pct_from_52w_low", PCT, nullable=True),
        sa.Column("above_ema_20", sa.Boolean(), nullable=True),
        sa.Column("above_ema_50", sa.Boolean(), nullable=True),
        sa.Column("above_ema_100", sa.Boolean(), nullable=True),
        sa.Column("above_ema_200", sa.Boolean(), nullable=True),
        sa.Column("feature_version", sa.String(32), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE",
                                name="fk_technical_features_stock_id_stocks"),
        sa.PrimaryKeyConstraint("stock_id", "date", name="pk_technical_features"),
    )
    op.create_index("ix_technical_features_date", "technical_features", ["date"])
    op.create_index("ix_technical_features_date_rel_volume",
                    "technical_features", ["date", "rel_volume"])

    # -- operations -----------------------------------------------------
    op.create_table(
        "scan_runs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("scan_date", sa.Date(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(16), nullable=False, server_default="RUNNING"),
        sa.Column("symbols_processed", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("symbols_failed", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("patterns_detected", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("breakouts_detected", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("engine_version", sa.String(48), nullable=False),
        sa.Column("universe_snapshot_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["universe_snapshot_id"], ["universe_snapshots.id"],
                                name="fk_scan_runs_universe_snapshot_id_universe_snapshots"),
    )
    op.create_index("ix_scan_runs_scan_date", "scan_runs", ["scan_date"])

    op.create_table(
        "data_quality_events",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("stock_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("severity", sa.String(8), nullable=False),
        sa.Column("category", sa.String(32), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("provider", sa.String(24), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE",
                                name="fk_data_quality_events_stock_id_stocks"),
    )
    op.create_index("ix_data_quality_events_severity_detected_at",
                    "data_quality_events", ["severity", "detected_at"])
    op.create_index("ix_data_quality_events_stock_id_date",
                    "data_quality_events", ["stock_id", "date"])

    upgrade_timescale()


def upgrade_timescale() -> None:
    """Convert ohlcv_daily to a hypertable. No-op off PostgreSQL.

    Kept as a separate function so the portable schema above stays readable
    and so a deployment can run it independently after enabling the extension.
    """
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    result = bind.execute(
        sa.text("SELECT 1 FROM pg_available_extensions WHERE name = 'timescaledb'")
    ).first()
    if result is None:
        return

    bind.execute(sa.text("CREATE EXTENSION IF NOT EXISTS timescaledb"))
    bind.execute(
        sa.text(
            "SELECT create_hypertable('ohlcv_daily', 'date', "
            "if_not_exists => TRUE, migrate_data => TRUE)"
        )
    )


def downgrade() -> None:
    for table in (
        "data_quality_events",
        "scan_runs",
        "technical_features",
        "ohlcv_daily",
        "universe_snapshots",
        "universe_members",
        "indices",
        "stocks",
        "industries",
        "sectors",
    ):
        op.drop_table(table)
