"""Phases 2-10: patterns, lifecycle, breakout ledger, product, backtests.

Autogenerated from the models and reviewed. Notable choices carried over from
the model definitions:

* ``pattern_events`` is append-only -- nothing updates a row, so replaying the
  log always reconstructs the status column.
* ``breakouts`` snapshots RS / sector rank / regime AT the breakout rather
  than joining them later, so recomputing those engines cannot rewrite what a
  past breakout looked like.
* ``backtest_runs.survivorship_mode`` is NOT NULL: a run that cannot say how
  its universe was resolved is not reproducible.
* ``ai_explanations.input_payload`` is NOT NULL: an explanation that cannot be
  audited against its inputs is not evidence of anything.


Revision ID: 0002
Revises: 0001
Create Date: 2026-09-14 13:31:12.120304
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=24), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_payload', sa.Text(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=False),
    sa.Column('engine_version_of_inputs', sa.String(length=48), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_explanations'))
    )
    with op.batch_alter_table('ai_explanations', schema=None) as batch_op:
        batch_op.create_index('ix_ai_explanations_subject', ['subject_type', 'subject_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('saved_screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_screens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_screens'))
    )
    with op.batch_alter_table('saved_screens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_screens_user_id'), ['user_id'], unique=False)

    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watchlists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlists')),
    sa.UniqueConstraint('user_id', 'name', name='uq_watchlists_user_id_name')
    )
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlists_user_id'), ['user_id'], unique=False)

    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('engine_version', sa.String(length=48), nullable=False),
    sa.Column('rule_version', sa.String(length=48), nullable=False),
    sa.Column('survivorship_mode', sa.String(length=24), nullable=False),
    sa.Column('survivorship_warning', sa.Text(), nullable=True),
    sa.Column('universe_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['universe_snapshot_id'], ['universe_snapshots.id'], name=op.f('fk_backtest_runs_universe_snapshot_id_universe_snapshots')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_backtest_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_runs'))
    )
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_runs_user_id'), ['user_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_alerts_stock_id_stocks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('costs', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('return_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('mfe_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('mae_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('days_held', sa.Integer(), nullable=True),
    sa.Column('entry_reason', sa.String(length=128), nullable=True),
    sa.Column('exit_reason', sa.String(length=48), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], name=op.f('fk_backtest_trades_run_id_backtest_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_backtest_trades_stock_id_stocks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_trades'))
    )
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.create_index('ix_backtest_trades_run_id_entry_date', ['run_id', 'entry_date'], unique=False)

    op.create_table('patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('pattern_type', sa.String(length=24), nullable=False),
    sa.Column('detected_on', sa.Date(), nullable=False),
    sa.Column('base_start', sa.Date(), nullable=False),
    sa.Column('base_end', sa.Date(), nullable=False),
    sa.Column('base_depth_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('base_duration_days', sa.Integer(), nullable=True),
    sa.Column('contraction_count', sa.Integer(), nullable=True),
    sa.Column('pivot_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('pivot_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('score_breakdown', sa.Text(), nullable=True),
    sa.Column('engine_version', sa.String(length=48), nullable=False),
    sa.Column('rule_version', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_patterns_stock_id_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patterns'))
    )
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.create_index('ix_patterns_status_score', ['status', 'score'], unique=False)
        batch_op.create_index('ix_patterns_stock_id_detected_on', ['stock_id', 'detected_on'], unique=False)

    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_watchlist_items_stock_id_stocks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], name=op.f('fk_watchlist_items_watchlist_id_watchlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist_items')),
    sa.UniqueConstraint('watchlist_id', 'stock_id', name='uq_watchlist_items_watchlist_id_stock_id')
    )
    op.create_table('alert_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('trigger_date', sa.Date(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_triggers_alert_id_alerts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_triggers'))
    )
    with op.batch_alter_table('alert_triggers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_triggers_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index('ix_alert_triggers_triggered_at', ['triggered_at'], unique=False)

    op.create_table('breakouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('breakout_date', sa.Date(), nullable=False),
    sa.Column('breakout_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('pivot_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('rel_volume', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rs_at_breakout', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sector_rank_at_breakout', sa.Integer(), nullable=True),
    sa.Column('regime_at_breakout', sa.String(length=16), nullable=True),
    sa.Column('setup_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('engine_version', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], name=op.f('fk_breakouts_pattern_id_patterns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_breakouts_stock_id_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_breakouts'))
    )
    with op.batch_alter_table('breakouts', schema=None) as batch_op:
        batch_op.create_index('ix_breakouts_breakout_date', ['breakout_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_breakouts_stock_id'), ['stock_id'], unique=False)

    op.create_table('pattern_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], name=op.f('fk_pattern_events_pattern_id_patterns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pattern_events'))
    )
    with op.batch_alter_table('pattern_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pattern_events_pattern_id'), ['pattern_id'], unique=False)

    op.create_table('breakout_outcomes',
    sa.Column('breakout_id', sa.Integer(), nullable=False),
    sa.Column('mfe_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('mae_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('days_held', sa.Integer(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('return_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('failed', sa.Boolean(), nullable=False),
    sa.Column('failure_date', sa.Date(), nullable=True),
    sa.Column('failure_reason', sa.String(length=48), nullable=True),
    sa.Column('days_to_failure', sa.Integer(), nullable=True),
    sa.Column('drawdown_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['breakout_id'], ['breakouts.id'], name=op.f('fk_breakout_outcomes_breakout_id_breakouts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('breakout_id', name=op.f('pk_breakout_outcomes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breakout_outcomes')
    with op.batch_alter_table('pattern_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pattern_events_pattern_id'))

    op.drop_table('pattern_events')
    with op.batch_alter_table('breakouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breakouts_stock_id'))
        batch_op.drop_index('ix_breakouts_breakout_date')

    op.drop_table('breakouts')
    with op.batch_alter_table('alert_triggers', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_triggers_triggered_at')
        batch_op.drop_index(batch_op.f('ix_alert_triggers_alert_id'))

    op.drop_table('alert_triggers')
    op.drop_table('watchlist_items')
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.drop_index('ix_patterns_stock_id_detected_on')
        batch_op.drop_index('ix_patterns_status_score')

    op.drop_table('patterns')
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.drop_index('ix_backtest_trades_run_id_entry_date')

    op.drop_table('backtest_trades')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_runs_user_id'))

    op.drop_table('backtest_runs')
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlists_user_id'))

    op.drop_table('watchlists')
    with op.batch_alter_table('saved_screens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_screens_user_id'))

    op.drop_table('saved_screens')
    op.drop_table('users')
    with op.batch_alter_table('ai_explanations', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_explanations_subject')

    op.drop_table('ai_explanations')
    # ### end Alembic commands ###
