"""Market context: relative strength, sector metrics, breadth, regime.

These four tables are what makes the read API a projection rather than a
computation. Without them every market/sector/RS endpoint would have to run
the engines inline while the user waits, which docs/09 section 1 forbids.

Notable choices:

* ``relative_strength.coverage`` and ``universe_size`` are stored alongside
  the score. A percentile is only meaningful against the population it was
  ranked in, and a rank computed from one horizon is a weaker claim than one
  computed from four -- both facts have to survive into the row.
* ``sector_metrics.rs_score`` is nullable. An unranked sector has no standing,
  which is not the same as standing last, and 0.0 would read as the latter.
* ``market_metrics.excluded`` counts universe members with no bar that day, so
  a breadth reading taken across a partial universe is identifiable as one.
* ``market_regimes.pending_regime`` records that a threshold was crossed and
  hysteresis withheld the change -- otherwise "stable" and "about to turn"
  look identical on read.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-14 13:40:14.540965
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('advancers', sa.Integer(), nullable=False),
    sa.Column('decliners', sa.Integer(), nullable=False),
    sa.Column('unchanged', sa.Integer(), nullable=False),
    sa.Column('ad_ratio', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('pct_above_ema_20', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pct_above_ema_50', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pct_above_ema_100', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pct_above_ema_200', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('new_highs_52w', sa.Integer(), nullable=False),
    sa.Column('new_lows_52w', sa.Integer(), nullable=False),
    sa.Column('breakouts', sa.Integer(), nullable=False),
    sa.Column('failed_breakouts', sa.Integer(), nullable=False),
    sa.Column('breakout_success_ratio', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('index_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('index_ret_1m', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('index_ret_3m', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('volatility_20d', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('universe_size', sa.Integer(), nullable=False),
    sa.Column('excluded', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=48), nullable=False),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_market_metrics'))
    )
    op.create_table('market_regimes',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('regime', sa.String(length=16), nullable=False),
    sa.Column('regime_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('trend_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('breadth_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('momentum_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('participation_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('volatility_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pending_regime', sa.String(length=16), nullable=True),
    sa.Column('engine_version', sa.String(length=48), nullable=False),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_market_regimes'))
    )
    op.create_table('sector_metrics',
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ret_1m', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('ret_3m', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('ret_6m', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('rs_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rs_rank', sa.Integer(), nullable=True),
    sa.Column('momentum_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('quadrant', sa.String(length=16), nullable=True),
    sa.Column('pct_above_ema_20', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pct_above_ema_50', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pct_above_ema_200', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('new_highs', sa.Integer(), nullable=False),
    sa.Column('new_lows', sa.Integer(), nullable=False),
    sa.Column('breakouts', sa.Integer(), nullable=False),
    sa.Column('failed_breakouts', sa.Integer(), nullable=False),
    sa.Column('avg_pattern_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('constituent_count', sa.Integer(), nullable=False),
    sa.Column('low_sample', sa.Boolean(), nullable=False),
    sa.Column('engine_version', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_sector_metrics_sector_id_sectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sector_id', 'date', name=op.f('pk_sector_metrics'))
    )
    with op.batch_alter_table('sector_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_sector_metrics_date_rs_rank', ['date', 'rs_rank'], unique=False)

    op.create_table('relative_strength',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ret_1m', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('ret_3m', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('ret_6m', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('ret_12m', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('rs_raw', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('rs_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rs_rank', sa.Integer(), nullable=True),
    sa.Column('rs_vs_sector', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rs_trend', sa.String(length=16), nullable=True),
    sa.Column('coverage', sa.String(length=64), nullable=True),
    sa.Column('universe_size', sa.Integer(), nullable=True),
    sa.Column('benchmark_index_id', sa.Integer(), nullable=True),
    sa.Column('engine_version', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_index_id'], ['indices.id'], name=op.f('fk_relative_strength_benchmark_index_id_indices')),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_relative_strength_stock_id_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stock_id', 'date', name=op.f('pk_relative_strength'))
    )
    with op.batch_alter_table('relative_strength', schema=None) as batch_op:
        batch_op.create_index('ix_relative_strength_date_rs_score', ['date', 'rs_score'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relative_strength', schema=None) as batch_op:
        batch_op.drop_index('ix_relative_strength_date_rs_score')

    op.drop_table('relative_strength')
    with op.batch_alter_table('sector_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_sector_metrics_date_rs_rank')

    op.drop_table('sector_metrics')
    op.drop_table('market_regimes')
    op.drop_table('market_metrics')
    # ### end Alembic commands ###
