"""Market structure: swings, BOS/CHoCH, order blocks, liquidity, FVG zones.

The SMC and FVG engines produced these during every scan and then discarded
them. Storing them is what lets the structure endpoints read rather than
recompute, and it is what makes a past structure reading auditable.

Notable choices:

* ``swing_points.confirmed_on`` is separate from ``date``. A swing is only
  knowable ``right_bars`` bars after it printed; a query that filters on
  ``date`` alone hands a backtest information it could not have had, which is
  the most common way an SMC backtest quietly becomes fiction.
* BOS and CHoCH share ``structure_breaks``. They are the same event shape and
  differ only in whether the break continued or reversed the prior structure;
  two tables would mean two query paths for one question.
* ``fvg_zones.mitigation_pct`` is a running maximum, never a current reading.
  A gap that filled 80% and then saw price retreat stays 80% mitigated --
  storing the live overlap would let a zone un-fill itself.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-14 13:53:10.012758
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fvg_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('created_at_bar', sa.Date(), nullable=False),
    sa.Column('upper_bound', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('lower_bound', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('size_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mitigation_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('mitigated_at', sa.Date(), nullable=True),
    sa.Column('engine_version', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_fvg_zones_stock_id_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fvg_zones')),
    sa.UniqueConstraint('stock_id', 'timeframe', 'created_at_bar', 'direction', name='uq_fvg_zones_stock_tf_bar_dir')
    )
    with op.batch_alter_table('fvg_zones', schema=None) as batch_op:
        batch_op.create_index('ix_fvg_zones_stock_id_timeframe_status', ['stock_id', 'timeframe', 'status'], unique=False)

    op.create_table('liquidity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('level', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=True),
    sa.Column('reclaimed', sa.Boolean(), nullable=False),
    sa.Column('linked_break_date', sa.Date(), nullable=True),
    sa.Column('engine_version', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_liquidity_events_stock_id_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_liquidity_events')),
    sa.UniqueConstraint('stock_id', 'timeframe', 'date', 'kind', 'level', name='uq_liquidity_events_stock_tf_date_kind_level')
    )
    with op.batch_alter_table('liquidity_events', schema=None) as batch_op:
        batch_op.create_index('ix_liquidity_events_stock_id_date', ['stock_id', 'date'], unique=False)

    op.create_table('order_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('upper', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('lower', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('origin_break_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mitigated_at', sa.Date(), nullable=True),
    sa.Column('engine_version', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_order_blocks_stock_id_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_blocks')),
    sa.UniqueConstraint('stock_id', 'timeframe', 'date', 'direction', name='uq_order_blocks_stock_tf_date_dir')
    )
    with op.batch_alter_table('order_blocks', schema=None) as batch_op:
        batch_op.create_index('ix_order_blocks_stock_id_status', ['stock_id', 'status'], unique=False)

    op.create_table('structure_breaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('broken_level', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('broken_swing_date', sa.Date(), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('prior_structure', sa.String(length=16), nullable=True),
    sa.Column('engine_version', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_structure_breaks_stock_id_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_structure_breaks')),
    sa.UniqueConstraint('stock_id', 'timeframe', 'date', 'kind', 'direction', name='uq_structure_breaks_stock_tf_date_kind_dir')
    )
    with op.batch_alter_table('structure_breaks', schema=None) as batch_op:
        batch_op.create_index('ix_structure_breaks_stock_id_date', ['stock_id', 'date'], unique=False)

    op.create_table('swing_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('swing_type', sa.String(length=8), nullable=False),
    sa.Column('strength', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('left_bars', sa.Integer(), nullable=False),
    sa.Column('right_bars', sa.Integer(), nullable=False),
    sa.Column('confirmed_on', sa.Date(), nullable=True),
    sa.Column('engine_version', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_swing_points_stock_id_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_swing_points')),
    sa.UniqueConstraint('stock_id', 'timeframe', 'date', 'swing_type', name='uq_swing_points_stock_tf_date_type')
    )
    with op.batch_alter_table('swing_points', schema=None) as batch_op:
        batch_op.create_index('ix_swing_points_stock_id_date', ['stock_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swing_points', schema=None) as batch_op:
        batch_op.drop_index('ix_swing_points_stock_id_date')

    op.drop_table('swing_points')
    with op.batch_alter_table('structure_breaks', schema=None) as batch_op:
        batch_op.drop_index('ix_structure_breaks_stock_id_date')

    op.drop_table('structure_breaks')
    with op.batch_alter_table('order_blocks', schema=None) as batch_op:
        batch_op.drop_index('ix_order_blocks_stock_id_status')

    op.drop_table('order_blocks')
    with op.batch_alter_table('liquidity_events', schema=None) as batch_op:
        batch_op.drop_index('ix_liquidity_events_stock_id_date')

    op.drop_table('liquidity_events')
    with op.batch_alter_table('fvg_zones', schema=None) as batch_op:
        batch_op.drop_index('ix_fvg_zones_stock_id_timeframe_status')

    op.drop_table('fvg_zones')
    # ### end Alembic commands ###
