"""User credentials: password hash and last login.

``password_hash`` is nullable, and that is load-bearing in two directions.
Existing rows predate local passwords and must not be invented one; the dev
identity and any externally-authenticated user legitimately have none. The
verifier therefore treats NULL as "cannot be authenticated by password",
never as "any password matches" -- the classic way a nullable credential
column becomes an authentication bypass.

Nothing here stores a password. The column holds a salted scrypt digest
(``scrypt$n$r$p$salt$hash``); the plaintext is never written and cannot be
recovered, only reset.

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-14 19:33:37.916165
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
